<a href="https://colab.research.google.com/github/yuviyadav-git/Miniprojects/blob/main/String_Cosine_Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This code finds the similarity between sentences, now i know that the movie recommendation(i just completed) is a far better project than this one, but this one is done by me without any help, while that one was me following a tutorial, i plan to do something similar to movie recommendation code, but on my own. I'll be free the next few days, so it will probably be complete by then.

In [2]:
!pip -q install sentence_transformers numpy

In [3]:
from sentence_transformers import SentenceTransformer
import numpy as np

In [5]:
max=5

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
sentences=[]
embeddings=[]
for i in range(0,max):
  sentence=input("Enter a sentence : ")
  sentences.append(sentence)
  embeddings.append(model.encode(sentence))

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Enter a sentence : i love pizza
Enter a sentence : i went to the bank
Enter a sentence : i am working for money
Enter a sentence : i adore pizza
Enter a sentence : i withdrew money


In [7]:
embedding_mat=[]

def similarity(v1,v2):
  return round(float(np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))),2)

for i in range(0,max):
  mat=[]
  for j in range(0,max):
    mat.append(similarity(embeddings[i],embeddings[j]))

  embedding_mat.append(mat)

for mat in embedding_mat:
  print(mat)

[1.0, 0.14, 0.13, 0.85, 0.12]
[0.14, 1.0, 0.41, 0.16, 0.59]
[0.13, 0.41, 1.0, 0.12, 0.42]
[0.85, 0.16, 0.12, 1.0, 0.13]
[0.12, 0.59, 0.42, 0.13, 1.0]


In [6]:
E = embeddings
E_norm = E / np.linalg.norm(E, axis=1, keepdims=True)
sim_matrix = E_norm @ E_norm.T

print(np.round(sim_matrix, 2))

[[1.   0.14 0.13 0.85 0.12]
 [0.14 1.   0.41 0.16 0.59]
 [0.13 0.41 1.   0.12 0.42]
 [0.85 0.16 0.12 1.   0.13]
 [0.12 0.59 0.42 0.13 1.  ]]


In the previous block, I added a much shorter and simpler code for similarity matrix, spending time on numpy initially is paying off now.

I will continue to try this format, ie, initially doing the code in an expanded form( it helps me understand), and later do the short and precise way, how the code should actually be done for easier reading and debugging.